### ISSUE TITLE
My SCSS/CSS edits are not showing up on my browser

### ISSUE THREAD

**Issue by chedie** [mechio/takana#42]
Good day,

I'm very new with Takana and I'm having a hard time making it work on any of my browsers.

Here is a breakdown of what I already did:

1. Had node, sass, takana installed in my Mac via CLI. Ruby was already there.

2. Installed Sublime Text 2 on Mac.

3. Installed Takana plugin in Sublime Text 2 via Sublime Package Control.

4. Via CLI, cd'd to my 'Sass' (for testing) directory.

5. Via CLI, typed takana . (now in my current directory)

6. Copied and pasted script snippet into my index.html
< script type="text/javascript" src="http://localhost:48626/takana.js" >< /script >
     < script type="text/javascript" >
       takanaClient.run(  {host: 'localhost:48626'}  );
     < /script >

7. On a separate CLI window, I did     sass --watch scss/stylesheet.scss:css/stylesheet.css

8. So a new .css file is compiled. Yay!

9. After everything, I then started editing stylesheet.scss in Sublime Text but the changes DON'T happen on my browser. But when I view my stylesheet.css, it shows my file is updated. Something like this:
body {
  background: white;
  color: blue; }

section {
  width: 500px; }

/*# sourceMappingURL=stylesheet.css.map */

So I'm really having a hard time trying to figure out how come my changes aren't happening instantaneously as it should. :(

Can anybody help me? Thank you.

**Comment by vulfox** [comment]
I also have to hover over the browser with the mouse to show the update.

or..

Have the mouse above browser window while typing and then hover _away_ from browser! 

Strange..

It might be it worked for a short while normally after starting

**Comment by barnaby** [comment]
Hey guys, I've pushed `0.4.1` which should fix the issue. Can anyone update and confirm?

**Comment by led** [comment]
Just updated to 0.4.1. It still isn't working for me. If I manually refresh the browser (Safari) I get a brief flash of the css style from the file, but that is then (presumably) overridden by takana and the style is removed. I can see that takana is registering my changes in Sublime (v3), but there's no change seem on the browser side at all.

**Comment by barnaby** [comment]
:(

Does it work for this (really simple) project https://github.com/barnaby/takana-test?

**Comment by afferently** [comment]
Hi, sorry not replying sooner.

I fount that my original issue was due to "shoe-horning" an existing project with Takana.

The project is in dev and had lots of separate stylesheets load in <head>

Once I changed this to one single file in <head> and used @import instead everything worked perfectly. I've been using the latest version too. It's so fast!

The only slight niggle is sometimes chrome doesn't update until you hover the cursor over it.

Safari doesn't seem to have this issue.

I think it could be because sometimes I have a project open in both safari and chrome simultaneously.

**Comment by led** [comment]
Hmm, well that's odd. I couldn't get the simple project working happily, but once I restarted my machine it's running very nicely... as is the project that failed previously. I don't know why it wasn't working the first time, but it is now! Thank you very much for your work on this.

**Comment by barnaby** [comment]
Happy to hear that it works!

@afferently hmm, I haven't seen that issue before but it seems to be separate from this one. Are you able to reproduce this reliably? Any chance you could file a new issue with steps?

@chedie have you tried with `0.4.2` to see if it fixes your issue?

**Comment by Talv** [comment]
I'm not sure if it's the same issue but in chrome changes doesn't show up instantaneously for me. I need to move cursor over browser, then it refresh. But if i have devtools tab opened it works as it should, so it's not a big deal.

**Comment by barnaby** [comment]
@Talv That's super weird. Few questions:

- What browser / version / os are you running? 
- Does this happen with all projects or only some? 
- Does it work with [mechio/takana-example](https://github.com/mechio/takana-example)?

**Comment by Talv** [comment]
Chrome 39.0.2171.95 ; Windows 7 SP1
It happened twice so far, on two different projects. It apppears unrelated to the project as i can run them now without issues, after restarting browser and takana.
Yes, it works on takana-example totally fine.

I'll keep testing and hopefully provide some useful informations to track it down eventually.

**Comment by barnaby** [comment]
Awesome, thanks. Keep me posted.

It's interesting that you're on Windows as well. Need to spin up a Windows VM and have a snoop around...

**Comment by joshuatf** [comment]
I was having this same issue (in linux) and spent about half my day pulling my hair out over it.  My projects would work at first and then some would suddenly stop working.  Everything was connected with no errors, but the log would say "buffer updated" without any change to the browser even on save.

In the end I realized I was working in a directory (/home/<user>/projects/)  that was a symbolic link to the actual files (/var/www/html).  This was causing a path mismatch between the working directory and the stylesheet path given by the browser.  The script was failing in takana/lib/server.coffee on lines 86-87:
```coffeescript
    @editorManager.on 'buffer:update', (data) =>
      return unless data.path.indexOf(@options.path) == 0 
```

I'm not sure if this is the same issues others are having or if this was just me being air-headed and missing the obvious.  It may be worth adding to the docs and/or adding a error log here though.

Either way, thanks for an awesome tool!

**Comment by alexadark** [comment]
Turning crazy, passed the day on that, learn grunt only for that (was very happy with codekit only) thinking perhaps it works only with grunt.
uninstall actual version, installed 0.0.10 and failed :-(
reinstall it.
tried everything nothing works, even nothing move in the console when i write in scss.
i pay anybody that can make it work on my mac trough teamviewer
cannot loose more time on this, too much to do, but i want it badly :-(
